#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

grep -lIREZ --exclude=".*" --exclude-dir=".*" "^ +$" | xargs -0 sed -Ei "s/^ +$//g"

find . -type f ! -path '.*/*' ! -name '.*' ! -name '*.md'
grep -lIREZ --exclude=".*" --exclude="*.md" --exclude-dir=".*" "^(.*[^ ]) +$" | xargs -0 sed -Ei "s/^(.*[^ ]) +$/\1/g"

cd - >/dev/null